#Todo o código em um arquivo YAML para ser utilizado como Infraestrutura como Código (IaC) usando o Serverless Framework.

service: my-serverless-service

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  region: sa-east-1

functions:
  createItem:
    handler: src/handlers/createItem.handler
    events:
      - http:
          method: post
          path: item

  getItem:
    handler: src/handlers/getItem.handler
    events:
      - http:
          method: get
          path: item/{id}

  listItems:
    handler: src/handlers/listItems.handler
    events:
      - http:
          method: get
          path: item

resources:
  Resources:
    ItemTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

  Outputs:
    ItemTable:
      Value:
        Ref: ItemTable
      Export:
        Name: ItemTable
